/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import islandScene from '../assets/3D/kou.glb'

const Island = (props) => {
    const islandRef = useRef();
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(islandScene)
  const { actions } = useAnimations(animations, group)
  return (
    <a.group ref={islandRef} {...props}>
      <group name="Scene">
        <group
          name="RootNode004"
          position={[0.995, 0.382, -1.321]}
          rotation={[-Math.PI, 0.625, -Math.PI]}
          scale={0.525}>
          <group name="AnimalArmature001" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body} />
            <primitive object={nodes.IKBackLegL} />
            <primitive object={nodes.IKFrontLegL} />
            <primitive object={nodes.IKBackLegR} />
            <primitive object={nodes.IKFrontLegR} />
          </group>
        </group>
        <group
          name="RootNode005"
          position={[0.995, 0.382, -1.321]}
          rotation={[-Math.PI, 0.625, -Math.PI]}
          scale={0.525}>
          <group name="AnimalArmature002" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body_1} />
            <primitive object={nodes.IKBackLegL_1} />
            <primitive object={nodes.IKFrontLegL_1} />
            <primitive object={nodes.IKBackLegR_1} />
            <primitive object={nodes.IKFrontLegR_1} />
          </group>
        </group>
        <group
          name="RootNode006"
          position={[0.995, 0.382, -1.321]}
          rotation={[-Math.PI, 0.625, -Math.PI]}
          scale={0.525}>
          <group name="AnimalArmature003" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body_2} />
            <primitive object={nodes.IKBackLegL_2} />
            <primitive object={nodes.IKFrontLegL_2} />
            <primitive object={nodes.IKBackLegR_2} />
            <primitive object={nodes.IKFrontLegR_2} />
          </group>
        </group>
        <group
          name="RootNode007"
          position={[0.995, 0.382, -1.321]}
          rotation={[-Math.PI, 0.625, -Math.PI]}
          scale={0.525}>
          <group name="AnimalArmature004" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <primitive object={nodes.Body_3} />
            <primitive object={nodes.IKBackLegL_3} />
            <primitive object={nodes.IKFrontLegL_3} />
            <primitive object={nodes.IKBackLegR_3} />
            <primitive object={nodes.IKFrontLegR_3} />
          </group>
        </group>
        <group name="cupTea" position={[2.875, 1.435, 0.822]} rotation={[0, 0.393, 0]}>
          <mesh
            name="cupTea_1"
            
            
            geometry={nodes.cupTea_1.geometry}
            material={materials._defaultMat}
          />
          <mesh
            name="cupTea_1_1"
            
            
            geometry={nodes.cupTea_1_1.geometry}
            material={materials.brownDarkest}
          />
        </group>
        <mesh
          name="group13306777"
          
          
          geometry={nodes.group13306777.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group14247407"
          
          
          geometry={nodes.group14247407.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group15835575"
          
          
          geometry={nodes.group15835575.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group59390808"
          
          
          geometry={nodes.group59390808.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group93335299"
          
          
          geometry={nodes.group93335299.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group156460083"
          
          
          geometry={nodes.group156460083.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group165613401"
          
          
          geometry={nodes.group165613401.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group192929773"
          
          
          geometry={nodes.group192929773.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group213039448"
          
          
          geometry={nodes.group213039448.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group225002350"
          
          
          geometry={nodes.group225002350.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group227914780"
          
          
          geometry={nodes.group227914780.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group238343898"
          
          
          geometry={nodes.group238343898.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group250223753"
          
          
          geometry={nodes.group250223753.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group256395068"
          
          
          geometry={nodes.group256395068.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group257976566"
          
          
          geometry={nodes.group257976566.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group283918997"
          
          
          geometry={nodes.group283918997.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group286116515"
          
          
          geometry={nodes.group286116515.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group370983626"
          
          
          geometry={nodes.group370983626.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group380733211"
          
          
          geometry={nodes.group380733211.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group423249565"
          
          
          geometry={nodes.group423249565.geometry}
          material={materials.mat21}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <group
          name="group430673059"
          position={[1.955, 1.98, 1.726]}
          rotation={[Math.PI, -0.821, Math.PI]}
          scale={0.528}>
          <mesh
            name="mesh430673059"
            
            
            geometry={nodes.mesh430673059.geometry}
            material={materials['mat17.001']}
          />
          <mesh
            name="mesh430673059_1"
            
            
            geometry={nodes.mesh430673059_1.geometry}
            material={materials.mat11}
          />
          <mesh
            name="mesh430673059_2"
            
            
            geometry={nodes.mesh430673059_2.geometry}
            material={materials['mat20.001']}
          />
          <mesh
            name="mesh430673059_3"
            
            
            geometry={nodes.mesh430673059_3.geometry}
            material={materials.mat10}
          />
          <mesh
            name="mesh430673059_4"
            
            
            geometry={nodes.mesh430673059_4.geometry}
            material={materials.mat8}
          />
          <mesh
            name="mesh430673059_5"
            
            
            geometry={nodes.mesh430673059_5.geometry}
            material={materials.mat25}
          />
          <mesh
            name="mesh430673059_6"
            
            
            geometry={nodes.mesh430673059_6.geometry}
            material={materials.mat15}
          />
          <mesh
            name="mesh430673059_7"
            
            
            geometry={nodes.mesh430673059_7.geometry}
            material={materials.mat16}
          />
        </group>
        <mesh
          name="group438200932"
          
          
          geometry={nodes.group438200932.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group505671632"
          
          
          geometry={nodes.group505671632.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group548630757"
          
          
          geometry={nodes.group548630757.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group552841683"
          
          
          geometry={nodes.group552841683.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group611048843"
          
          
          geometry={nodes.group611048843.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group633143504"
          
          
          geometry={nodes.group633143504.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group633938376"
          
          
          geometry={nodes.group633938376.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group634255084"
          
          
          geometry={nodes.group634255084.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group687955143"
          
          
          geometry={nodes.group687955143.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group728145106"
          
          
          geometry={nodes.group728145106.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <group
          name="group742438179"
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}>
          <mesh
            name="mesh742438179"
            
            
            geometry={nodes.mesh742438179.geometry}
            material={materials.mat21}
          />
          <mesh
            name="mesh742438179_1"
            
            
            geometry={nodes.mesh742438179_1.geometry}
            material={materials.mat18}
          />
          <mesh
            name="mesh742438179_2"
            
            
            geometry={nodes.mesh742438179_2.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh742438179_3"
            
            
            geometry={nodes.mesh742438179_3.geometry}
            material={materials.mat17}
          />
          <mesh
            name="mesh742438179_4"
            
            
            geometry={nodes.mesh742438179_4.geometry}
            material={materials.mat23}
          />
          <mesh
            name="mesh742438179_5"
            
            
            geometry={nodes.mesh742438179_5.geometry}
            material={materials.mat22}
          />
          <mesh
            name="mesh742438179_6"
            
            
            geometry={nodes.mesh742438179_6.geometry}
            material={materials.mat20}
          />
        </group>
        <mesh
          name="group751481862"
          
          
          geometry={nodes.group751481862.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group752053113"
          
          
          geometry={nodes.group752053113.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group752636525"
          
          
          geometry={nodes.group752636525.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group802050906"
          
          
          geometry={nodes.group802050906.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group842451926"
          
          
          geometry={nodes.group842451926.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group864707251"
          
          
          geometry={nodes.group864707251.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group875940139"
          
          
          geometry={nodes.group875940139.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group905252152"
          
          
          geometry={nodes.group905252152.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group935609718"
          
          
          geometry={nodes.group935609718.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group937831915"
          
          
          geometry={nodes.group937831915.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group962457873"
          
          
          geometry={nodes.group962457873.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group966664866"
          
          
          geometry={nodes.group966664866.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1003306018"
          
          
          geometry={nodes.group1003306018.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1011320071"
          
          
          geometry={nodes.group1011320071.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1011911227"
          
          
          geometry={nodes.group1011911227.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1017517075"
          
          
          geometry={nodes.group1017517075.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1019897031"
          
          
          geometry={nodes.group1019897031.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1034316329"
          
          
          geometry={nodes.group1034316329.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1048815158"
          
          
          geometry={nodes.group1048815158.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1052635492"
          
          
          geometry={nodes.group1052635492.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1138996592"
          
          
          geometry={nodes.group1138996592.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <group
          name="group1140854425"
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}>
          <mesh
            name="mesh1140854425"
            
            
            geometry={nodes.mesh1140854425.geometry}
            material={materials.mat20}
          />
          <mesh
            name="mesh1140854425_1"
            
            
            geometry={nodes.mesh1140854425_1.geometry}
            material={materials.mat23}
          />
          <mesh
            name="mesh1140854425_2"
            
            
            geometry={nodes.mesh1140854425_2.geometry}
            material={materials.mat22}
          />
          <mesh
            name="mesh1140854425_3"
            
            
            geometry={nodes.mesh1140854425_3.geometry}
            material={materials.mat19}
          />
          <mesh
            name="mesh1140854425_4"
            
            
            geometry={nodes.mesh1140854425_4.geometry}
            material={materials.mat18}
          />
          <mesh
            name="mesh1140854425_5"
            
            
            geometry={nodes.mesh1140854425_5.geometry}
            material={materials.mat17}
          />
          <mesh
            name="mesh1140854425_6"
            
            
            geometry={nodes.mesh1140854425_6.geometry}
            material={materials.mat21}
          />
        </group>
        <mesh
          name="group1146959302"
          
          
          geometry={nodes.group1146959302.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1220427099"
          
          
          geometry={nodes.group1220427099.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1269888978"
          
          
          geometry={nodes.group1269888978.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1277222791"
          
          
          geometry={nodes.group1277222791.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1331048207"
          
          
          geometry={nodes.group1331048207.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1357238172"
          
          
          geometry={nodes.group1357238172.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1359852237"
          
          
          geometry={nodes.group1359852237.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1366047388"
          
          
          geometry={nodes.group1366047388.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1370981756"
          
          
          geometry={nodes.group1370981756.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1387497183"
          
          
          geometry={nodes.group1387497183.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1447785718"
          
          
          geometry={nodes.group1447785718.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1479453844"
          
          
          geometry={nodes.group1479453844.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1484951833"
          
          
          geometry={nodes.group1484951833.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1497847545"
          
          
          geometry={nodes.group1497847545.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1573889920"
          
          
          geometry={nodes.group1573889920.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1632347617"
          
          
          geometry={nodes.group1632347617.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1662040012"
          
          
          geometry={nodes.group1662040012.geometry}
          material={materials.mat18}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1692817625"
          
          
          geometry={nodes.group1692817625.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1699351704"
          
          
          geometry={nodes.group1699351704.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1702132102"
          
          
          geometry={nodes.group1702132102.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1721710528"
          
          
          geometry={nodes.group1721710528.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1751088038"
          
          
          geometry={nodes.group1751088038.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1782243135"
          
          
          geometry={nodes.group1782243135.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1793352265"
          
          
          geometry={nodes.group1793352265.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1798431221"
          
          
          geometry={nodes.group1798431221.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1812224903"
          
          
          geometry={nodes.group1812224903.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1838312899"
          
          
          geometry={nodes.group1838312899.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1839125294"
          
          
          geometry={nodes.group1839125294.geometry}
          material={materials.mat22}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1849838348"
          
          
          geometry={nodes.group1849838348.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1884002018"
          
          
          geometry={nodes.group1884002018.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1938683590"
          
          
          geometry={nodes.group1938683590.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1967720642"
          
          
          geometry={nodes.group1967720642.geometry}
          material={materials.mat21}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1972613599"
          
          
          geometry={nodes.group1972613599.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1987144854"
          
          
          geometry={nodes.group1987144854.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group1994798792"
          
          
          geometry={nodes.group1994798792.geometry}
          material={materials.mat17}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group2006398532"
          
          
          geometry={nodes.group2006398532.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group2015271255"
          
          
          geometry={nodes.group2015271255.geometry}
          material={materials.mat23}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group2040108076"
          
          
          geometry={nodes.group2040108076.geometry}
          material={materials.mat20}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <mesh
          name="group2095556955"
          
          
          geometry={nodes.group2095556955.geometry}
          material={materials.mat19}
          position={[1.017, 1.982, 1.435]}
          rotation={[Math.PI, -0.977, Math.PI]}
          scale={0.681}
        />
        <group name="Node" position={[1.586, 0.506, -2.367]} scale={0.5}>
          <mesh
            name="Node-Mesh"
            
            
            geometry={nodes['Node-Mesh'].geometry}
            material={materials['mat23.001']}
          />
          <mesh
            name="Node-Mesh_1"
            
            
            geometry={nodes['Node-Mesh_1'].geometry}
            material={materials['mat15.001']}
          />
          <mesh
            name="Node-Mesh_2"
            
            
            geometry={nodes['Node-Mesh_2'].geometry}
            material={materials['mat22.001']}
          />
          <mesh
            name="Node-Mesh_3"
            
            
            geometry={nodes['Node-Mesh_3'].geometry}
            material={materials['mat25.001']}
          />
          <mesh
            name="Node-Mesh_4"
            
            
            geometry={nodes['Node-Mesh_4'].geometry}
            material={materials.mat4}
          />
          <mesh
            name="Node-Mesh_5"
            
            
            geometry={nodes['Node-Mesh_5'].geometry}
            material={materials.mat3}
          />
        </group>
        <group name="RootNode" position={[-0.713, 0.397, -0.892]} scale={1.487}>
          <group
            name="Chair"
            position={[-1.115, 0.67, 0.437]}
            rotation={[-Math.PI / 2, 0, 1.643]}
            scale={3.082}>
            <mesh
              name="Chair_1"
              
              
              geometry={nodes.Chair_1.geometry}
              material={materials['Executive.003']}
            />
            <mesh
              name="Chair_2"
              
              
              geometry={nodes.Chair_2.geometry}
              material={materials['Executive__1.003']}
            />
            <mesh
              name="Chair_3"
              
              
              geometry={nodes.Chair_3.geometry}
              material={materials['Executive__2.003']}
            />
            <mesh
              name="Chair_4"
              
              
              geometry={nodes.Chair_4.geometry}
              material={materials['Executive__3.003']}
            />
          </group>
          <mesh
            name="Computer_mouse"
            
            
            geometry={nodes.Computer_mouse.geometry}
            material={materials.ComputerMouse_mat1}
            position={[-0.566, 0.92, 0.91]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={2.93}
          />
          <group
            name="Computer_Screen"
            position={[-0.111, 0.919, 0.472]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={154.397}>
            <mesh
              name="Computer_Screen_1"
              
              
              geometry={nodes.Computer_Screen_1.geometry}
              material={materials.metalDark}
            />
            <mesh
              name="Computer_Screen_2"
              
              
              geometry={nodes.Computer_Screen_2.geometry}
              material={materials['metal.002']}
            />
          </group>
          <group
            name="Cube002"
            position={[-0.111, 0.945, 1.079]}
            rotation={[-Math.PI / 2, 0, 3.106]}
            scale={[6.489, 9.4, 0.204]}>
            <mesh
              name="Cube003"
              
              
              geometry={nodes.Cube003.geometry}
              material={materials['Material.009']}
            />
            <mesh
              name="Cube003_1"
              
              
              geometry={nodes.Cube003_1.geometry}
              material={materials['Material.010']}
            />
          </group>
          <group
            name="Cylinder001"
            position={[-0.094, 1.409, 0.484]}
            rotation={[0, -Math.PI / 2, 0]}
            scale={6.449}>
            <mesh
              name="Cylinder004"
              
              
              geometry={nodes.Cylinder004.geometry}
              material={materials['Grey.002']}
            />
            <mesh
              name="Cylinder004_1"
              
              
              geometry={nodes.Cylinder004_1.geometry}
              material={materials.Dark}
            />
            <mesh
              name="Cylinder004_2"
              
              
              geometry={nodes.Cylinder004_2.geometry}
              material={materials.Blue}
            />
            <mesh
              name="Cylinder004_3"
              
              
              geometry={nodes.Cylinder004_3.geometry}
              material={materials['Material.011']}
            />
          </group>
          <group
            name="Desk-V86Go2rlnq"
            position={[-0.778, 0.916, 0.419]}
            rotation={[-Math.PI, 1.571, 0]}
            scale={[9999.999, 9999.996, 9999.996]}>
            <mesh
              name="Desk-V86Go2rlnq_1"
              
              
              geometry={nodes['Desk-V86Go2rlnq_1'].geometry}
              material={materials['DarkWood.012']}
            />
            <mesh
              name="Desk-V86Go2rlnq_2"
              
              
              geometry={nodes['Desk-V86Go2rlnq_2'].geometry}
              material={materials['Wood.013']}
            />
          </group>
          <mesh
            name="Keyboard-aPwr5p1dluw"
            
            
            geometry={nodes['Keyboard-aPwr5p1dluw'].geometry}
            material={materials['Mat.065']}
            position={[-0.552, 0.919, 0.416]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.625}
          />
          <group
            name="Laptop_bag"
            position={[-0.556, 0.009, -0.604]}
            rotation={[-1.407, 0, -Math.PI]}
            scale={0}>
            <mesh
              name="Laptop_bag_1"
              
              
              geometry={nodes.Laptop_bag_1.geometry}
              material={materials['02___Default.049']}
            />
            <mesh
              name="Laptop_bag_2"
              
              
              geometry={nodes.Laptop_bag_2.geometry}
              material={materials['03___Default.025']}
            />
            <mesh
              name="Laptop_bag_3"
              
              
              geometry={nodes.Laptop_bag_3.geometry}
              material={materials['_crayfishdiffuse.049']}
            />
            <mesh
              name="Laptop_bag_4"
              
              
              geometry={nodes.Laptop_bag_4.geometry}
              material={materials['_crayfishdiffuse-2.012']}
            />
          </group>
          <group
            name="Light_Desk"
            position={[-0.135, 1.162, -0.245]}
            rotation={[-Math.PI / 2, 0, 2.301]}
            scale={[8561.474, 8561.473, 8561.471]}>
            <mesh
              name="Light_Desk_1"
              
              
              geometry={nodes.Light_Desk_1.geometry}
              material={materials['Black.097']}
            />
            <mesh
              name="Light_Desk_2"
              
              
              geometry={nodes.Light_Desk_2.geometry}
              material={materials['LightMetal.027']}
            />
            <mesh
              name="Light_Desk_3"
              
              
              geometry={nodes.Light_Desk_3.geometry}
              material={materials['White.053']}
            />
          </group>
          <mesh
            name="Mousepad002"
            
            
            geometry={nodes.Mousepad002.geometry}
            material={materials['Mousepad.001']}
            position={[-0.561, 0.919, 0.771]}
            scale={[1175.398, 15.54, 1430.879]}
          />
          <group
            name="Office_Phone002"
            position={[-0.328, 0.973, -0.086]}
            rotation={[Math.PI, 1.424, 0]}
            scale={626.776}>
            <mesh
              name="Office_Phone002_1"
              
              
              geometry={nodes.Office_Phone002_1.geometry}
              material={materials['Light grey']}
            />
            <mesh
              name="Office_Phone002_2"
              
              
              geometry={nodes.Office_Phone002_2.geometry}
              material={materials['Grey Plastic']}
            />
            <mesh
              name="Office_Phone002_3"
              
              
              geometry={nodes.Office_Phone002_3.geometry}
              material={materials.Screen}
            />
            <mesh
              name="Office_Phone002_4"
              
              
              geometry={nodes.Office_Phone002_4.geometry}
              material={materials['Dark Grey Plastic']}
            />
          </group>
          <group
            name="System_unit001"
            position={[-0.4, 0.244, -0.257]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={0.162}>
            <mesh
              name="System_unit001_1"
              
              
              geometry={nodes.System_unit001_1.geometry}
              material={materials.lambert3SG}
            />
            <mesh
              name="System_unit001_2"
              
              
              geometry={nodes.System_unit001_2.geometry}
              material={materials.initialShadingGroup}
            />
          </group>
        </group>
        <group
          name="RootNode001"
          position={[1.091, 0.385, -3.21]}
          rotation={[Math.PI, -0.295, Math.PI]}
          scale={1.802}>
          <mesh
            name="Mailbox"
            geometry={nodes.Mailbox.geometry}
            material={materials['Material.012']}
            position={[-0.044, 0, -0.05]}
            rotation={[0, -0.697, 0]}
            scale={133.035}
          />
        </group>
        <group
          name="RootNode002"
          position={[1.663, 0.959, -0.47]}
          rotation={[0, 0.412, 0]}
          scale={0.685}>
          <mesh
            name="Environment_Cabinet_Shelves"
            geometry={nodes.Environment_Cabinet_Shelves.geometry}
            material={materials['Atlas.001']}
            position={[-0.075, 0, 2.762]}
            rotation={[0, 0.393, 0]}
            scale={100}
          />
        </group>
        <group
          name="RootNode003"
          position={[0.995, 0.382, -1.321]}
          rotation={[-Math.PI, 0.625, -Math.PI]}
          scale={0.525}>
          <group name="AnimalArmature" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <group name="ShibaInu">
              <skinnedMesh
                name="ShibaInu_1"
                geometry={nodes.ShibaInu_1.geometry}
                material={materials.Main}
                skeleton={nodes.ShibaInu_1.skeleton}
              />
              <skinnedMesh
                name="ShibaInu_2"
                geometry={nodes.ShibaInu_2.geometry}
                material={materials.Main_Light}
                skeleton={nodes.ShibaInu_2.skeleton}
              />
              <skinnedMesh
                name="ShibaInu_3"
                geometry={nodes.ShibaInu_3.geometry}
                material={materials.Black}
                skeleton={nodes.ShibaInu_3.skeleton}
              />
              <skinnedMesh
                name="ShibaInu_4"
                geometry={nodes.ShibaInu_4.geometry}
                material={materials.Eyes_White}
                skeleton={nodes.ShibaInu_4.skeleton}
              />
              <skinnedMesh
                name="ShibaInu_5"
                geometry={nodes.ShibaInu_5.geometry}
                material={materials.Eyes_Pupil}
                skeleton={nodes.ShibaInu_5.skeleton}
              />
              <skinnedMesh
                name="ShibaInu_6"
                geometry={nodes.ShibaInu_6.geometry}
                material={materials.Eyes_Black}
                skeleton={nodes.ShibaInu_6.skeleton}
              />
            </group>
            <primitive object={nodes.Body_4} />
            <primitive object={nodes.IKBackLegL_4} />
            <primitive object={nodes.IKFrontLegL_4} />
            <primitive object={nodes.IKBackLegR_4} />
            <primitive object={nodes.IKFrontLegR_4} />
          </group>
        </group>
        <group name="rugRound" position={[4.203, 0.338, -4.237]} scale={8.387}>
          <mesh
            name="rugRound_2"
            geometry={nodes.rugRound_2.geometry}
            material={materials.carpet}
          />
          <mesh
            name="rugRound_2_1"
            geometry={nodes.rugRound_2_1.geometry}
            material={materials.carpetDarker}
          />
        </group>
        <group name="Cylinder" position={[0.321, 0.246, -0.459]} scale={[4.807, 0.072, 4.807]}>
          <mesh
            name="Cylinder001_1"
            geometry={nodes.Cylinder001_1.geometry}
            material={materials['Material.006']}
          />
          <mesh
            name="Cylinder001_2"
            geometry={nodes.Cylinder001_2.geometry}
            material={materials['Material.008']}
          />
        </group>
      </group>
    </a.group>
  )
}

useGLTF.preload('/kou.glb')

export default Island;
